---

- name: Update Known Hosts [{{ prop_installipaddress }}]
  shell: |
    {{ role_path }}/scripts/known.hosts.sh "{{ prop_installipaddress }}" "{{ prop_local_user_ssh }}"
    if [[ "$?" != "0" ]]; then
      echo "Error executing script" 
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: '"Changed" in result.stdout'
  failed_when: '"Error" in result.stdout'
  vars:
    ansible_python_interpreter: "{{ prop_local_python }}"
  connection: local
  become: false
