---

- name: "Playbook: Test IP Lease"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # waitstarted
        name: alex.base.getiplease
